### ISSUE TITLE
[BUG] Cannot import graspologic (python 3.7.9)

### ISSUE THREAD

**Issue by kareef928** [microsoft/graspologic#890]
## Example Code
```python
import graspologic
```

## Full Traceback
```pytb
Traceback (most recent call last):
  File "/Users/kareefullah/Desktop/Graspy_Workspace/graspologic/test copy.py", line 1, in <module>
    import graspologic
  File "/Users/kareefullah/Desktop/Graspy_Workspace/graspologic/graspologic/__init__.py", line 7, in <module>
    import graspologic.embed
  File "/Users/kareefullah/Desktop/Graspy_Workspace/graspologic/graspologic/embed/__init__.py", line 11, in <module>
    from .n2v import node2vec_embed
  File "/Users/kareefullah/Desktop/Graspy_Workspace/graspologic/graspologic/embed/n2v.py", line 11, in <module>
    from gensim.models import Word2Vec
  File "/opt/miniconda3/envs/kullah/lib/python3.7/site-packages/gensim/__init__.py", line 11, in <module>
    from gensim import parsing, corpora, matutils, interfaces, models, similarities, utils  # noqa:F401
  File "/opt/miniconda3/envs/kullah/lib/python3.7/site-packages/gensim/corpora/__init__.py", line 6, in <module>
    from .indexedcorpus import IndexedCorpus  # noqa:F401 must appear before the other classes
  File "/opt/miniconda3/envs/kullah/lib/python3.7/site-packages/gensim/corpora/indexedcorpus.py", line 14, in <module>
    from gensim import interfaces, utils
  File "/opt/miniconda3/envs/kullah/lib/python3.7/site-packages/gensim/interfaces.py", line 19, in <module>
    from gensim import utils, matutils
  File "/opt/miniconda3/envs/kullah/lib/python3.7/site-packages/gensim/matutils.py", line 1024, in <module>
    from gensim._matutils import logsumexp, mean_absolute_difference, dirichlet_expectation
  File "gensim/_matutils.pyx", line 1, in init gensim._matutils
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```

## Your Environment
* Python version: 3.7.9
* graspologic version: cannot check

**Comment by bdpedigo** [comment]
thanks @kareef928

can you provide the output of `pip list`?

**Comment by kareef928** [comment]
```
Package            Version                 Editable project location
------------------ ----------------------- -------------------------------------------------------
anytree            2.8.0
appdirs            1.4.4
appnope            0.1.0
argon2-cffi        20.1.0
astroid            2.4.2
attrs              20.2.0
backcall           0.2.0
beartype           0.8.1
black              20.8b1
bleach             3.1.5
blosc              1.10.1
certifi            2020.6.20
cffi               1.14.2
chardet            4.0.0
click              7.1.2
coverage           5.3.1
cycler             0.10.0
Cython             0.29.21
decorator          4.4.2
defusedxml         0.6.0
entrypoints        0.3
gensim             4.1.2
graspologic        0.1.0.dev20201002125733 /Users/kareefullah/Desktop/Graspy_Workspace/graspologic
graspologic_native 0.1.0
graspy             0.3.0                   /Users/kareefullah/Desktop/Graspy_Workspace/graspologic
hyppo              0.2.1
idna               2.10
iniconfig          1.0.1
intern             1.2.0
ipykernel          5.3.4
ipython            7.18.1
ipython-genutils   0.2.0
ipywidgets         7.5.1
isort              4.3.21
jedi               0.17.2
Jinja2             2.11.2
joblib             0.16.0
jsonschema         3.2.0
jupyter            1.0.0
jupyter-client     6.1.7
jupyter-console    6.2.0
jupyter-core       4.6.3
kiwisolver         1.2.0
lazy-object-proxy  1.4.3
llvmlite           0.34.0
MarkupSafe         1.1.1
matplotlib         3.3.0
mccabe             0.6.1
mistune            0.8.4
mock               4.0.3
more-itertools     8.5.0
mypy-extensions    0.4.3
nbconvert          5.6.1
nbformat           5.0.7
networkx           2.5
nose               1.3.7
nose2              0.9.2
notebook           6.1.3
numba              0.51.2
numpy              1.19.1
packaging          20.4
pandas             1.1.1
pandocfilters      1.4.2
parso              0.7.1
pathspec           0.8.0
pexpect            4.8.0
pickleshare        0.7.5
Pillow             7.2.0
pip                21.3.1
pluggy             0.13.1
POT                0.7.0
prometheus-client  0.8.0
prompt-toolkit     3.0.7
ptyprocess         0.6.0
py                 1.9.0
pycparser          2.20
Pygments           2.6.1
pylint             2.5.3
pyparsing          2.4.7
pyrsistent         0.16.0
pytest             6.1.2
python-dateutil    2.8.1
pytz               2020.1
pyzmq              19.0.2
qtconsole          4.7.7
QtPy               1.9.0
regex              2020.7.14
requests           2.25.1
scikit-learn       0.23.2
scikit-network     0.22.0
scipy              1.5.2
seaborn            0.11.0rc0
Send2Trash         1.5.0
setuptools         47.1.0
six                1.15.0
smart-open         5.2.1
terminado          0.8.3
testpath           0.4.4
threadpoolctl      2.1.0
toml               0.10.1
tornado            6.0.4
traitlets          5.0.4
typed-ast          1.4.1
typing-extensions  3.7.4.3
umap               0.1.1
urllib3            1.26.2
wcwidth            0.2.5
webencodings       0.5.1
widgetsnbextension 3.5.1
wrapt              1.12.1
zmesh              0.4.0
```

**Comment by daxpryce** [comment]
```
graspologic        0.1.0.dev20201002125733 /Users/kareefullah/Desktop/Graspy_Workspace/graspologic
graspologic_native 0.1.0
```
are pretty ancient versions.  I assume this is an older venv?
